import os
import pandas as pd
import numpy as np
import joblib
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report)

#These are the paths to the files produced by prepare_data.py
TRAIN_DATA_PATH = "data/train_clean.csv"
TEST_DATA_PATH = "data/test_clean.csv"
SCALER_PATH = "data/scaler_params.csv"
MODEL_SAVE_PATH = "data/ids_model.joblib" #where AI model is saved

#The 7 feature columns model is using (need to be same as variables in prepare_data.py)
FEATURE_COLS= ["packet_count", "avg_packet_size", "duration", "failed_logins", "requests_per_sec", "unusual_port" , "data_volume"]

#Classification threshol
THRESHOLD = 0.35

#Load preprocessed training data CSV generated by prepare_data.py
#Returns X and Y where X is a 2d array with each row being a network connection and Y being a 1D array of 0s and 1s (attacks)
def load_training_data():
    print("Loading training data...")
    df = pd.read_csv(TRAIN_DATA_PATH)
    x = df[FEATURE_COLS].values
    y = df["label"].values
    print(f"Loaded {len(x)} training rows")
    return x, y

#This loads the preprocessed test CSV from prepare_data.py
#This data is seperate from training and simulates real-world activity
def load_test_data():
     print("Loading test data... ")
     df = pd.read_csv(TEST_DATA_PATH)
     x = df[FEATURE_COLS].values
     y = df["label"].values
     print(f"Loaded {len(x)} test rows")
     return x, y
    
#This loads the min/max scaling parameters that were saved during data preparation
#Used during normalisation of live traffic events to make sure theyre scaled using correct parameters
#Returns a dictionary - {feature_name: (min_value, max_value)}
def load_scaler_params():
    df = pd.read_csv(SCALER_PATH)
    params = {}
    for _, row in df.iterrows():
        params[row["feature"]] = (row["min"], row["max"])
    return params

#This trains the logistic regression model from provided training data
#Some paramters explained:
    # max_iter=1000 - maximum optimisation iterations
    # C=1.0 - strenth of regularisation (lower = stronger regularisation and prevents overfitting from data)
    # random_state=42 - makes training reproducible
    # class_weight="balanced" - automatically adjusts weights to handle imbalanced datasets
def train_model(x_train, y_train):
    print("Training logistic regression model...")
    model = LogisticRegression(
        max_iter=1000,
        C=1.0,
        random_state=42,
        class_weight="balanced")
    model.fit(x_train, y_train)
    print("Training complete")
    return model
    
#This saves the trained model to disk using joblib and makes it so UI doesnt need to retrain model each time it starts up
def save_model(model):
    os.makedirs("data", exist_ok=True)
    joblib.dump(model, MODEL_SAVE_PATH)
    print(f"Model saved to {MODEL_SAVE_PATH}")
    
#This loads previous model from disk and called from UI
#If model isnt trained then it raises a FileNotFoundError
def load_model():
    if not os.path.exists(MODEL_SAVE_PATH):
        raise FileNotFoundError(
            f"No trained model found at {MODEL_SAVE_PATH}.\n"
            f"Please run model.py first to train and save the model.")
    model = joblib.load(MODEL_SAVE_PATH)
    print(f"Model loaded from {MODEL_SAVE_PATH}")
    return model

#Evaluated the trained model using test set and prints a report of performance metrics
def evaluate_model(model, x_test, y_test):
    print("\nEvaluating model on test data...")
    probabilities = model.predict_proba(x_test)[:,1] #Attack probability column
    y_pred = (probabilities >= THRESHOLD).astype(int) #Applies our threshold: anything above 0.35 is a threat (1)
    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred, zero_division=0)
    recall = recall_score(y_test, y_pred, zero_division=0)
    f1 = f1_score(y_test, y_pred, zero_division=0)
    #Confusion matrix layout:
    #              Predicted Normal  |  Predicted Attack
    #Actual Normal       TN          |       FP
    #Actual Attack       FN          |       TP
    cm = confusion_matrix(y_test, y_pred)
    tn, fp, fn, tp = cm.ravel() #unpacks the 4 values
    #Generate report
    print("\n")
    print(" MODEL EVALUATION REPORT")
    print("="*50)
    print(f" Classification threshold : {THRESHOLD}")
    print(f" Test set size            : {len(y_test)} rows")
    print("="*50)
    print(f" Accuracy                 : {accuracy:.4f} ({accuracy*100:.1f}%)")
    print(f" Precision                : {precision:.4f} ({precision*100:.1f}%)")
    print(f" Recall                   : {recall:.4f} ({recall*100:.1f}%)")
    print(f" F1 Score                 : {f1:.4f} ({f1*100:.1f}%)")
    print("-"*50)
    print(" Confusion Matrix:")
    print(f"   True Positives  (TP) : {tp} (attacks correctly caught)")
    print(f"   True Negatives  (TN) : {tn} (normal traffic correctly passed)")
    print(f"   False Positives (FP) : {fp} (normal traffic incorrectly flagged)")
    print(f"   False Negatives (FN) : {fn} (attacks incorrectly missed)")
    print("="*50)
    #Warning if recall is below the target set in the project objectives
    if recall < 0.90:
        print(f" WARNING: Recall {recall:.2f} is below the 90% target")
        print(" Consider lowering threshold or rebalancing training data")
    else:
        print(f" Recall target (>=90%) MET: {recall:.2f}")
    #return all metrics as a dictionary so UI can display them
    return {
        "accuracy": round(accuracy, 4),
        "precision": round(precision, 4),
        "recall": round(recall, 4),
        "f1": round(f1, 4),
        "tp": int(tp),
        "tn": int(tn),
        "fp": int(fp),
        "fn": int(fn),
        "threshold": THRESHOLD,
        "test_size": len(y_test)}

#Prints the weight (coefficient) the model learned for each feature
#High positive weight means the feature strongly indicates an attack, whereas a negative weight means higher values of that feature suggest normal traffic
def print_feature_weights(model):
    print()
    print("Feature Weights (coefficents):")
    print("  "+"-"*40)
    weights = model.coef_[0] #model.coef is a 2d array but for binary classification theres only 1 row is [0] is used
    sorted_pairs = sorted(zip(FEATURE_COLS, weights),
                          key=lambda x: abs(x[1]), reverse=True) #This sorts features by absolute weight
    for feature, weight in sorted_pairs:
        direction = "-> attack" if weight > 0 else "-> normal"
        print(f"  {feature:<20} {weight:+.4f} {direction}")
    
#This normalises a single live network event using min/max parameters from training for a consistant input
#event_dict - dictionary with keys matching FEATURE_COLS
#scaler_params - dictionary from load_scaler_params()
#Returns a 2d numpy array with shape (1,7) to pass to model.predict.proba()
def normalise_live_event(event_dict, scaler_params):
    feature_values = []
    for feature in FEATURE_COLS:
        raw_value = event_dict.get(feature, 0) #defualts to 0 if missing
        min_val, max_val = scaler_params.get(feature, (0,1))
        if max_val == min_val:
            scaled = 0.0 #edge case: feature always has same value -> set to 0
        else:
            scaled = (raw_value - min_val)/(max_val - min_val)
            scaled = float(np.clip(scaled, 0.0, 1.0))# clip() ensures result is within [0,1]
        feature_values.append(scaled)
    return np.array(feature_values).reshape(1,-1) #reshapes to (1,7)

#This takes a raw network event and runs it through prediction system
#1) normalise features
#2) goes through logistic regression
#3) gets probability score
#4) apply threshold for classification
#5) returns probability and classification
#Returns a tuple (probability, classification)
def predict_event(model, event_dict, scaler_params):
    x = normalise_live_event(event_dict, scaler_params)
    probability = model.predict_proba(x)[0][1]
    if probability < THRESHOLD:
        classification = "Normal"
    elif probability < 0.70:
        classification ="Medium"
    else:
        classification = "High"
    return round(probability, 4), classification

#This runs the full training pipeline
#1) load training + test data
#2) train the model
#3) print features weights
#4) evaluate on test data
#5) save model to disk

def main():
    print("AI-IDS Model Training")
    print("="*60)
    if not os.path.exists(TRAIN_DATA_PATH):
        print("\nERROR: Training data not found")
        print("Please run prepary_data.py first")
        return
    print()
    x_train, y_train = load_training_data()
    x_test, y_test = load_test_data()
    print()
    model = train_model(x_train, y_train)
    print_feature_weights(model)
    metrics = evaluate_model(model, x_test, y_test)
    print("\nSaving Model...")
    save_model(model)
    print("Training complete! You can now run ui.py.")

if __name__ == "__main__":
    main()